name: C3ML_Azure_Test_NR
on: workflow_dispatch
env:
  TEST_NAME: '"C3ML_Azure_Test_NR_V1.2"'
  WORKSPACE_NAME: '"C3ML_Azure_Test_NR"'
  VERSION: 'AZURE Test C3ML NR'
  NL_REPOSITORY: 'huangbinocp/C3ML_Azure_Test_NR'
  NL_SCENARIO: 'C3ML_Azure_Test_NR_All_Scripts'
jobs:  
  app_dev_tirs:
    name: C3ML_Azure_TEST_NR Tirs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - api_url: https://neoload-api.saas.neotys.com/
            token: C3ML_AZURE_GIT
    steps:
      - name: "1. Checkout Neoload project repository"
        uses: actions/checkout@master
        with:
         repository: ${{ env.NL_REPOSITORY }}
         token: ${{ secrets.MY_PAT }}
      - name: "2. Zip Neoload Folder"
        run: zip -r NL_Script.zip . -x ".git/*" ".github/*"
      - name: "3. Install NeoLoad CLI"
        run: pip3 install -U neoload
      - name: "4. Prepare NeoLoad test"
        run: >
          neoload login --url ${{ matrix.api_url }} --workspace ${{ env.WORKSPACE_NAME }} ${{ secrets[matrix.token] }} \
                  test-settings --scenario ${{ env.NL_SCENARIO }} createorpatch ${{ env.TEST_NAME }} \
                  project --path NL_Script.zip upload
      - name: "5. NeoLoad run test"
        run: >
          neoload run 
          --external-url $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID 
          --external-url-label "Github Action Run ${{ env.VERSION }}.$GITHUB_RUN_NUMBER" 
          --name "C3ML Silamir Test sur AZURE - Github build ${{ env.VERSION }}.$GITHUB_RUN_NUMBER" 
          --description "Test de performance avec paramètres prédéfinis (10 VUs pendant 2 minutes) ou personnalisés." 
          --reservation-duration 2400
          ${{ env.TEST_NAME }}
